### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by HardHat-Det** [cristianoc20/Rebar_Detection#9]
您好，现在还有这个数据集，比赛地址里面的数据集下载总是失败

**Comment by cristianoc20** [comment]
readme里面有百度云

**Comment by HardHat-Det** [comment]
> readme里面有百度云

我看介绍百度云里面是权值文件

**Comment by cristianoc20** [comment]
数据集链接：https://pan.baidu.com/s/1V0s9oc1_FSNCKgRkyutU2w 提取码：hh4i 之前看漏了 不好意思兄弟

**Comment by HardHat-Det** [comment]
您客气了
